---
title: "About Me"
---

## Background

I grew up in the Philadelphia area and graduated from Wharton in 2021 with concentrations in statistics and business economics/public policy. I've been working at Penn since then as the Assistant Director for [PORES](https://www.pores.upenn.edu) and the [Fox Leadership Program](https://foxleadership.upenn.edu) on campus. I hope to work as a data scientist in the public sector in the future.

I started on my Master's in Data Science last fall and am excited to expand on my background in quantitative political science research in this course. I'm looking forward to learning more about spatial analysis and applying my programming and research skills to interesting datasets.


## Skills

<!-- CHANGE THIS: update this through the semester as it becomes true -->

- **Languages & Tools:** R, Git, Python, Java
- **Spatial:** 
- **Data:** US Census / ACS via `tidycensus`

## Contact

- Email: stkath@upenn.edu
- GitHub: [@steelekatie](https://github.com/steelekatie)
