{
  "hash": "acdf8cd855b1d7cb9a2db93fec74caf9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Katie Steele\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\nparams:\n  state: \"AZ\"\n---\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n\n## The question\n\nEvery number the American Community Survey publishes is an estimate drawn from a sample, not a count. That means every number comes with a margin of error — a statement about how wrong it might be.\n\nMost people ignore it. In this assignment, you won't.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#my_state <- \"AZ\"        # two-letter abbreviation, in quotes\nmy_variable <- \"B01002_001\"     # the variable code, in quotes\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = params$state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 15  5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                     variable   estimate   moe\n  <chr> <chr>                    <chr>         <dbl> <dbl>\n1 04001 Apache County, Arizona   B01002_001     36.2   0.3\n2 04003 Cochise County, Arizona  B01002_001     42.9   0.5\n3 04005 Coconino County, Arizona B01002_001     32.4   0.2\n4 04007 Gila County, Arizona     B01002_001     51.4   0.5\n5 04009 Graham County, Arizona   B01002_001     34.4   0.3\n6 04011 Greenlee County, Arizona B01002_001     36.1   0.8\n```\n\n\n:::\n:::\n\n\n\nThere are 15 counties in Arizona; the call to `get_acs()` retrieved them all.\n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an estimate of 20,000\nthan for an estimate of 200,000. To compare across places, we need it as a\npercentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\nNow sort to see which counties are measured least reliably.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                       estimate   moe moe_pct\n   <chr>                         <dbl> <dbl>   <dbl>\n 1 Greenlee County, Arizona       36.1   0.8   2.22 \n 2 La Paz County, Arizona         59.7   0.8   1.34 \n 3 Cochise County, Arizona        42.9   0.5   1.17 \n 4 Santa Cruz County, Arizona     37.9   0.4   1.06 \n 5 Navajo County, Arizona         39.4   0.4   1.02 \n 6 Gila County, Arizona           51.4   0.5   0.973\n 7 Graham County, Arizona         34.4   0.3   0.872\n 8 Apache County, Arizona         36.2   0.3   0.829\n 9 Coconino County, Arizona       32.4   0.2   0.617\n10 Yuma County, Arizona           35.8   0.2   0.559\n```\n\n\n:::\n:::\n\n\nGreenlee County has the largest relative margin of error at 2.22%. \n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 0.6  ~ \"High confidence\",\n    moe_pct < 1.2 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence     6\n2 Low confidence      2\n3 Moderate            7\n```\n\n\n:::\n:::\n\n\n\nGrouping counties based on `moe_pct` confidence (high: [0-0.6%); moderate: [0.6% - 1.2%); low otherwise), we see that 6 counties have highly reliable estimates, 7 are moderately reliable, and only 2 counties fall into the low-reliability group.\n\n\n## Is the margin of error bigger in small places?\n\nTo answer this we need population and our variable side by side, in the same row. That means a **wide** pull.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = params$state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                     myvarE myvarM   popE  popM\n  <chr> <chr>                     <dbl>  <dbl>  <dbl> <dbl>\n1 04001 Apache County, Arizona     36.2    0.3  65680    NA\n2 04003 Cochise County, Arizona    42.9    0.5 125458    NA\n3 04005 Coconino County, Arizona   32.4    0.2 144643    NA\n4 04007 Gila County, Arizona       51.4    0.5  53610    NA\n5 04009 Graham County, Arizona     34.4    0.3  38860    NA\n6 04011 Greenlee County, Arizona   36.1    0.8   9452    NA\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 0.6  ~ \"High confidence\",\n    moe_pct < 1.2 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow compare the average population of counties in each reliability category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence          6       1109652.\n2 Low confidence           2         13028.\n3 Moderate                 7         83458.\n```\n\n\n:::\n:::\n\n\nThis table clearly shows that ACS estimates for median age are least reliable in counties with small populations. The relative margin of error is highest in small counties and decreases as counties grow in mean population.\n\n\n## What this means for policy\n\nWe know the least about the two smallest counties in Arizona, Greenlee and La Paz, which make up the \"low confidence\" `moe_pct` category. The ACS samples 2-3% of U.S. households annually -- and response rates are lower than that -- so in Greenlee, with a population of 9,452, the 5-year estimate is likely based on only a couple hundred households. This leads to a higher sampling error than in larger counties. \n\nSince sparsely populated counties have the highest sampling error, their estimates are noisier than those in denser areas. Maricopa County, which is one of the largest counties in the United States, has an `moe_pct` of only 0.27%, meaning we're 95% certain that the true median age in Maricopa is within ~1 month of the estimate (37.5 years). Greenlee County has an `moe_pct` of 2.22%; with an estimated median age of 36.2 years, we can only narrow down the true median age to a much wider ~10-month window at the 95% confidence level.\n\nThis could have big implications for policymaking. If funding or resource allocation is determined based on a specific cutoff point or threshold, and estimates are treated as equally precise across counties, small counties are most likely to be hurt, since we see more fluctuation and uncertainty in their estimates as a result of smaller sample sizes.\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}